### ISSUE TITLE
Simplify usage of zsh/bash/fish auto-completions

### ISSUE THREAD

**Issue by jmfayard** [jmfayard/kotlin-cli-starter#3]
The program could auto-detect that the bash/zsh/fish completion files and regenerate them

Figure out in which folders they should be put

**Comment by NikkyAI** [comment]
docs for fish: https://fishshell.com/docs/current/#initialization-files

**Comment by jmfayard** [comment]
I've found how to do it with homebrew, but they don't allow submission of your own work, closing the issue for now since I don't know what to do
https://github.com/jmfayard/kotlin-cli-starter/issues/4

If you have an idea, please re-open
